MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.5 ]
  GPU_IDS: [ 0 ]

DATASETS:
  TRAIN: "/data/sharedata/clean_pretrain_data/"
  VALID: ""
  TEST: "datasets/bbcm_dynamicP/test.json"

SOLVER:
  BASE_LR: 1e-4
  WEIGHT_DECAY: 5e-8
  BATCH_SIZE: 16
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4

DATALOADER:
  NUM_WORKERS: 4

TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"
  FIXED: false

OUTPUT_DIR: "checkpoints/b_findoc_dynamicP"
